# Usar una imagen oficial de Node.js
FROM node:14

# Crear el directorio de la aplicación en el contenedor
WORKDIR /usr/src/app

# Copiar package.json y package-lock.json al contenedor
COPY package*.json ./

# Instalar las dependencias en el contenedor
RUN npm install

# Copiar el resto de los archivos de la aplicación al contenedor
COPY . .

# Exponer el puerto 3000 para que otros servicios puedan comunicarse con nuestra aplicación
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD [ "npm", "start" ]
